<?php


function cvl_visualization_help($path, $arg) {
  switch ($path) {
    case "help.page.cvl_visualization":
      return t("Visualization tool for CVL");
      break;
  }
}





function cvl_parse_related_information_resource($rir) {
    $related_information_resource = [];
    foreach ($rir as $rir_elem) {
        $la = explode(':', $rir_elem, 2);
        $protocol = str_replace('"', '', $la[0]);
        $ma = explode(',', $la[1], 2);
        $uri = str_replace('"', '', $ma[0]);
        $na = explode(':', $ma[1], 2);
        $description_name = str_replace('"', '', $na[0]);
        $description_value = str_replace('"', '', $na[1]);
        $related_information_resource[$protocol]['uri'] = $uri;
        $related_information_resource[$protocol][$description_name] = $description_value;
    } return $related_information_resource;
}

function cvl_parse_solr_mmd_type_one($metadata_element) {

  $element_array = [];
  if (is_array($metadata_element)) {
    foreach ($metadata_element as $k => $v) {
      $la = explode(",", $v);
      $lal = explode(":", $la[0], 2);
      $lar = explode(":", $la[1], 2);
      $element_array[$lal[0]] = str_replace(array('"'), '', $lal[1]);
      $element_array[$lal[0] . " " . $lar[0]] = $lar[1];
    }
  } return $element_array;
}
